id: AAA30A01D
title: Concise Middle Way Aspiration
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:43:18.312499
  last_modified_at: 2022-03-01 04:43:18.312506
